name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pylint
        pip install numpy
        pip install pandas
        pip install scipy
        pip install pytest
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files 'setup.py')
        pylint --disable=E1101,W0212 $(git ls-files 'tests/test_hstransform.py')
        pylint --disable=E1101 $(git ls-files 'tests/__init__.py')
        pylint --disable=E1101 $(git ls-files 'hstransform.py')
